### ISSUE TITLE
What is grover?

### ISSUE THREAD

**Issue by mcab** [salesforce/lobster-pot#10]
Hi there!

Stumbled upon the project, and I'm curious about this mentioned tool called `grover`:

- https://github.com/salesforce/lobster-pot/blob/77e2282943754fd749c97a2ce24747fa15fe8c41/scanner/grover.go
- https://github.com/salesforce/lobster-pot/blob/77e2282943754fd749c97a2ce24747fa15fe8c41/config/scanner.go#L67-L76

[Scanner configuration documentation](https://github.com/salesforce/lobster-pot/blob/77e2282943754fd749c97a2ce24747fa15fe8c41/docs/configuration/scanner.md) states to look in `docs/scanner` for information, but `grover` isn't there. Is there any documentation / link to this tool?

**Comment by DocEmmetBrown** [comment]
Hi @mcab,
Thanks for your comment.
`grover` is a custom tool that we're using for scanning purposes.
